os: linux
dist: xenial
language: python
python: 3.7

before_install:
 - python3 -m pip install --upgrade pip wheel poetry
 - python3 --version
 - pip3 --version

install:
 - poetry install

script:
 - "make test"
 - "make typecheck"
