[tool.poetry]
name = "qslang"
version = "0.1.0"
description = ""
authors = ["Erik Bjäreholt <erik@bjareho.lt>"]
license = "MPL-2.0"
packages = [
    { include = "qslang" }
]

[tool.poetry.scripts]
qslang = "qslang:__main__"

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.18.0"
matplotlib = "^3.1"
pandas = "^1.2"
calmap = "*"
pint = "^0.9"
toml = "^0.10.0"
click = "^7.0"

[tool.poetry.dev-dependencies]
pytest = "^6.0"
mypy = "*"
flake8 = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
