[tool.poetry]
name = "qslang"
version = "0.1.0"
description = ""
authors = ["Erik Bjäreholt <erik@bjareho.lt>"]
license = "MPL-2.0"
packages = [
    { include = "qslang" }
]

[tool.poetry.scripts]
qslang = "qslang.main:main"

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.18.0"
matplotlib = "^3.1.2"
pandas = "^1.0.3"
calmap = "^0.0.8"
pint = "^0.9"
toml = "^0.10.0"
click = "^7.0"

[tool.poetry.dev-dependencies]
pytest = "^5.3.2"
mypy = "^0.761"
flake8 = "^3.7.9"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
