[tool.poetry]
name = "qslang"
version = "0.1.0"
description = ""
authors = ["Erik Bjäreholt <erik@bjareho.lt>"]
license = "MPL-2.0"
packages = [
    { include = "qslang" }
]

[tool.poetry.scripts]
qslang = "qslang:__main__"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "*"
matplotlib = "*"
pandas = "*"
pint = "*"
toml = "*"
click = "*"
calplot = "^0.1"  # fork of calmap

[tool.poetry.dev-dependencies]
pytest = "*"
mypy = "*"
flake8 = "*"
black = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
